package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"ti/builtin"
	"unicode"
)

func main() {
	matches, err := filepath.Glob(".ti-config/*.json")
	if err != nil || len(matches) == 0 {
		fmt.Fprintln(os.Stderr, "no JSON files found in .ti-config/")
		os.Exit(1)
	}

	var classDefs []builtin.ClassDefinition
	for _, match := range matches {
		data, err := os.ReadFile(match)
		if err != nil {
			fmt.Fprintf(os.Stderr, "read error %s: %v\n", match, err)
			os.Exit(1)
		}
		if len(data) == 0 {
			continue
		}
		var cd builtin.ClassDefinition
		if err := json.Unmarshal(data, &cd); err != nil {
			fmt.Fprintf(os.Stderr, "parse error %s: %v\n", match, err)
			os.Exit(1)
		}
		classDefs = append(classDefs, cd)
	}

	// Pre-compute function names to ensure consistency
	names := make([]string, len(classDefs))
	counter := 0
	for i, cd := range classDefs {
		names[i] = classToFuncName(cd.Class, cd.Frame, &counter)
	}

	var buf bytes.Buffer
	fmt.Fprintln(&buf, "// Code generated by cmd/gen_builtins. DO NOT EDIT.")
	fmt.Fprintln(&buf)
	fmt.Fprintln(&buf, "package builtin")
	fmt.Fprintln(&buf)
	fmt.Fprintln(&buf, "func LoadForStdin() {")
	for _, name := range names {
		fmt.Fprintf(&buf, "\t%s()\n", name)
	}
	fmt.Fprintln(&buf, "}")

	for i, cd := range classDefs {
		fmt.Fprintln(&buf)
		renderClassFunc(&buf, names[i], cd)
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		fmt.Fprintf(os.Stderr, "format error: %v\ngenerated:\n%s\n", err, buf.String())
		os.Exit(1)
	}

	if err := os.WriteFile("builtin/stdin_types.go", formatted, 0644); err != nil {
		fmt.Fprintf(os.Stderr, "write error: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("generated builtin/stdin_types.go (%d classes)\n", len(classDefs))
}

func classToFuncName(class, _ string, counter *int) string {
	var b strings.Builder
	for _, r := range class {
		if unicode.IsLetter(r) || unicode.IsDigit(r) {
			b.WriteRune(r)
		}
	}
	name := b.String()
	if name == "" {
		*counter++
		name = fmt.Sprintf("Object%d", *counter)
	}
	return "load" + name
}

func renderClassFunc(buf *bytes.Buffer, name string, cd builtin.ClassDefinition) {
	fmt.Fprintf(buf, "func %s() {\n", name)
	fmt.Fprintf(buf, "\tloadClassDef(ClassDefinition{\n")
	fmt.Fprintf(buf, "\t\tFrame: %s,\n", strconv.Quote(cd.Frame))
	fmt.Fprintf(buf, "\t\tClass: %s,\n", strconv.Quote(cd.Class))

	if len(cd.InstanceMethods) > 0 {
		fmt.Fprintf(buf, "\t\tInstanceMethods: []MethodDefinition{\n")
		for _, m := range cd.InstanceMethods {
			renderMethodDef(buf, m, "\t\t\t")
		}
		fmt.Fprintf(buf, "\t\t},\n")
	}

	if len(cd.ClassMethods) > 0 {
		fmt.Fprintf(buf, "\t\tClassMethods: []MethodDefinition{\n")
		for _, m := range cd.ClassMethods {
			renderMethodDef(buf, m, "\t\t\t")
		}
		fmt.Fprintf(buf, "\t\t},\n")
	}

	if len(cd.Constants) > 0 {
		fmt.Fprintf(buf, "\t\tConstants: []ConstDefinition{\n")
		for _, c := range cd.Constants {
			fmt.Fprintf(buf, "\t\t\t{Name: %s, ReturnType: %s},\n",
				strconv.Quote(c.Name), renderMethodReturn(c.ReturnType))
		}
		fmt.Fprintf(buf, "\t\t},\n")
	}

	if len(cd.Extends) > 0 {
		fmt.Fprintf(buf, "\t\tExtends: []string{")
		for i, e := range cd.Extends {
			if i > 0 {
				fmt.Fprintf(buf, ", ")
			}
			fmt.Fprintf(buf, "%s", strconv.Quote(e))
		}
		fmt.Fprintf(buf, "},\n")
	}

	if len(cd.InstanceProperties) > 0 {
		fmt.Fprintf(buf, "\t\tInstanceProperties: []PropertyDefinition{\n")
		for _, p := range cd.InstanceProperties {
			fmt.Fprintf(buf, "\t\t\t{Name: %s, Type: %s, Access: %s},\n",
				strconv.Quote(p.Name), renderTypeSpec(p.Type), strconv.Quote(p.Access))
		}
		fmt.Fprintf(buf, "\t\t},\n")
	}

	if len(cd.InstanceVariables) > 0 {
		fmt.Fprintf(buf, "\t\tInstanceVariables: []InstanceVarDefinition{\n")
		for _, iv := range cd.InstanceVariables {
			fmt.Fprintf(buf, "\t\t\t{Name: %s, Type: %s},\n",
				strconv.Quote(iv.Name), renderTypeSpec(iv.Type))
		}
		fmt.Fprintf(buf, "\t\t},\n")
	}

	fmt.Fprintf(buf, "\t})\n")
	fmt.Fprintf(buf, "}\n")
}

func renderMethodDef(buf *bytes.Buffer, m builtin.MethodDefinition, indent string) {
	fmt.Fprintf(buf, "%s{\n", indent)
	fmt.Fprintf(buf, "%s\tName: %s,\n", indent, strconv.Quote(m.Name))

	if len(m.BlockParameters) > 0 {
		fmt.Fprintf(buf, "%s\tBlockParameters: []string{", indent)
		for i, bp := range m.BlockParameters {
			if i > 0 {
				fmt.Fprintf(buf, ", ")
			}
			fmt.Fprintf(buf, "%s", strconv.Quote(bp))
		}
		fmt.Fprintf(buf, "},\n")
	}

	if len(m.Arguments) > 0 {
		fmt.Fprintf(buf, "%s\tArguments: []MethodArgument{\n", indent)
		for _, a := range m.Arguments {
			fmt.Fprintf(buf, "%s\t\t%s,\n", indent, renderMethodArg(a))
		}
		fmt.Fprintf(buf, "%s\t},\n", indent)
	}

	fmt.Fprintf(buf, "%s\tReturnType: %s,\n", indent, renderMethodReturn(m.ReturnType))

	if m.Document != "" {
		fmt.Fprintf(buf, "%s\tDocument: %s,\n", indent, strconv.Quote(m.Document))
	}

	fmt.Fprintf(buf, "%s},\n", indent)
}

func renderMethodArg(a builtin.MethodArgument) string {
	var parts []string
	if len(a.Type) > 0 {
		parts = append(parts, "Type: "+renderTypeSpec(a.Type))
	}
	if a.Key != "" {
		parts = append(parts, "Key: "+strconv.Quote(a.Key))
	}
	if a.IsAsterisk {
		parts = append(parts, "IsAsterisk: true")
	}
	if a.IsDefault {
		parts = append(parts, "IsDefault: true")
	}
	return "MethodArgument{" + strings.Join(parts, ", ") + "}"
}

func renderMethodReturn(r builtin.MethodReturn) string {
	var parts []string
	if len(r.Type) > 0 {
		parts = append(parts, "Type: "+renderTypeSpec(r.Type))
	}
	if r.IsConditionalReturn {
		parts = append(parts, "IsConditionalReturn: true")
	}
	if r.IsDestructive {
		parts = append(parts, "IsDestructive: true")
	}
	if r.IsCaptureOwner {
		parts = append(parts, "IsCaptureOwner: true")
	}
	return "MethodReturn{" + strings.Join(parts, ", ") + "}"
}

func renderTypeSpec(ts builtin.TypeSpec) string {
	if len(ts) == 0 {
		return "nil"
	}
	var parts []string
	for _, s := range ts {
		parts = append(parts, strconv.Quote(s))
	}
	return "TypeSpec{" + strings.Join(parts, ", ") + "}"
}
